@host = 

###
POST {{host}}
Content-Type: application/json

{
    "email": "",
    "password": "",
    "id_list": [
        "sm43937640",
        "sm44167259",
        "sm44683022",
        "sm43166484",
        "sm44541693",
        "sm44661043",
        "sm42636474",
        "sm44862177",
        "sm40352352",
        "sm18358647"
    ],
    "subscription": "{\"endpoint\":\"https://fcm.googleapis.com/fcm/send/test\",\"keys\":{\"p256dh\":\"test_key\",\"auth\":\"test_auth\"}}"
}
