AWSTemplateFormatVersion: "2010-09-09"
Description: AWS Batch for NMA Register Batch

Parameters:
  EcrRepositoryUri:
    Type: String
    Description: ECR repository URI
  SubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
    Description: Subnets
  SecurityGroupIds:
    Type: List<String>
    Description: Security group ids

Resources:
  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /aws/ecs/niconico-mylist-assistant-register-batch
      RetentionInDays: 7

  TaskExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
      Tags:
        - Key: Name
          Value: niconico-mylist-assistant-register-batch-task-execution-role
      RoleName: niconico-mylist-assistant-register-batch-task-execution-role

  TaskRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      Path: /
      Tags:
        - Key: Name
          Value: niconico-mylist-assistant-register-batch-task-role
      RoleName: niconico-mylist-assistant-register-batch-task-role

  BatchServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: batch.amazonaws.com
            Action: sts:AssumeRole
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSBatchServiceRole
      Tags:
        - Key: Name
          Value: niconico-mylist-assistant-register-batch-service-role
      RoleName: niconico-mylist-assistant-register-batch-service-role

  BatchComputeEnvironment:
    Type: AWS::Batch::ComputeEnvironment
    Properties:
      Type: MANAGED
      ServiceRole: !GetAtt BatchServiceRole.Arn
      ComputeResources:
        Type: FARGATE
        MaxvCpus: 32
        Subnets: !Ref SubnetIds
        SecurityGroupIds: !Ref SecurityGroupIds
      State: ENABLED

  BatchJobQueue:
    Type: AWS::Batch::JobQueue
    Properties:
      Priority: 1
      State: ENABLED
      ComputeEnvironmentOrder:
        - Order: 1
          ComputeEnvironment: !Ref BatchComputeEnvironment
      JobQueueName: niconico-mylist-assistant-register-batch-queue

  BatchJobDefinition:
    Type: AWS::Batch::JobDefinition
    Properties:
      Type: container
      PlatformCapabilities:
        - FARGATE
      ContainerProperties:
        Image: !Sub "${EcrRepositoryUri}:latest"
        ResourceRequirements:
          - Type: VCPU
            Value: "16"
          - Type: MEMORY
            Value: "65536"
        ExecutionRoleArn: !GetAtt TaskExecutionRole.Arn
        JobRoleArn: !GetAtt TaskRole.Arn
        NetworkConfiguration:
          AssignPublicIp: ENABLED
        LogConfiguration:
          LogDriver: awslogs
          Options:
            awslogs-group: !Ref LogGroup
            awslogs-region: !Ref "AWS::Region"
            awslogs-stream-prefix: register-batch
        Environment:
          - Name: AWS_DEFAULT_REGION
            Value: !Ref "AWS::Region"
      RetryStrategy:
        Attempts: 1
      Timeout:
        AttemptDurationSeconds: 600
      JobDefinitionName: niconico-mylist-assistant-register-batch-jobdef
