name: Manager対応
description: Manager 関連の作業する Issue テンプレート
title: "[Manager] "
labels: ["Manager"]
body:
  - type: markdown
    attributes:
      value: |
        ## 注意事項
        作業は必ず **manager ディレクトリ配下** で行ってください。
  - type: textarea
    id: policy
    attributes:
      label: 対応方針
      description: この Issue の対応方針を記載してください
    validations:
      required: false
