AWSTemplateFormatVersion: "2010-09-09"
Description: IAM User and Policy for GitHub Actions

Resources:
  GitHubActionsUser:
    Type: AWS::IAM::User
    Properties:
      UserName: niconico-mylist-assistant-github-actions-user
      Path: /niconico-mylist-assistant/

  GitHubActionsPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: niconico-mylist-assistant-github-actions
      Users:
        - !Ref GitHubActionsUser
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - cloudformation:*
            Resource: "*"
          - Effect: Allow
            Action:
              - ec2:*
            Resource: "*"
          - Effect: Allow
            Action:
              - ecr:*
            Resource: "*"
          - Effect: Allow
            Action:
              - lambda:*
            Resource: "*"
