AWSTemplateFormatVersion: '2010-09-09'
Description: ECS resources for NMA Register Batch (dev) - Fargate service with public IP

Parameters:
  TaskExecutionRoleArn:
    Type: String
    Description: ARN of the Task Execution Role
  TaskRoleArn:
    Type: String
    Description: ARN of the Task Role
  SecurityGroupId:
    Type: String
    Description: Security Group ID for ECS tasks
  EcrRepositoryUri:
    Type: String
    Description: ECR repository URI

Resources:
  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /aws/ecs/dev-niconico-mylist-assistant-register-batch
      RetentionInDays: 7

  Cluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: dev-niconico-mylist-assistant-register-batch-cluster

  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: dev-niconico-mylist-assistant-register-batch-task
      Cpu: 4096
      Memory: 11264
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      ExecutionRoleArn: !Ref TaskExecutionRoleArn
      TaskRoleArn: !Ref TaskRoleArn
      ContainerDefinitions:
        - Name: dev-niconico-mylist-assistant-register-batch
          Image: !Sub "${EcrRepositoryUri}:latest"
          Essential: true
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref LogGroup
              awslogs-region: !Ref "AWS::Region"
              awslogs-stream-prefix: register-batch
          Environment:
            - Name: AWS_ACCESS_KEY_ID
              Value: ""
            - Name: AWS_SECRET_ACCESS_KEY
              Value: ""
            - Name: AWS_DEFAULT_REGION
              Value: ""
            - Name: NICONICO_EMAIL
              Value: ""
            - Name: NICONICO_PASSWORD
              Value: ""
            - Name: NICONICO_ID_LIST
              Value: ""
            - Name: NOTIFICATION_API_ENDPOINT
              Value: ""
            - Name: PUSH_SUBSCRIPTION
              Value: ""
            - Name: S3_BUCKET_NAME
              Value: ""

Outputs:
  ClusterName:
    Description: ECS Cluster name
    Value: !Ref Cluster

# To deploy this template, run:
# aws cloudformation deploy \
#   --template-file register-batch/aws/dev/ecs.yaml \
#   --stack-name dev-niconico-mylist-assistant-register-batch-ecs \
#   --parameter-overrides \
#     TaskExecutionRoleArn=<TaskExecutionRoleArn-from-iam-stack> \
#     TaskRoleArn=<TaskRoleArn-from-iam-stack> \
#     SecurityGroupId=<SecurityGroupId-from-vpc-stack> \
#     EcrRepositoryUri=<RepositoryUri-from-ecr-stack>
