AWSTemplateFormatVersion: '2010-09-09'
Description: IAM roles for NMA Register Batch (dev) ECS tasks

Resources:
  TaskExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
      Tags:
        - Key: Name
          Value: dev-niconico-mylist-assistant-register-batch-task-execution-role
      RoleName: dev-niconico-mylist-assistant-register-batch-task-execution-role

  TaskRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      Path: /
      Tags:
        - Key: Name
          Value: dev-niconico-mylist-assistant-register-batch-task-role
      RoleName: dev-niconico-mylist-assistant-register-batch-task-role

Outputs:
  TaskExecutionRoleArn:
    Description: ARN of the Task Execution Role
    Value: !GetAtt TaskExecutionRole.Arn

  TaskRoleArn:
    Description: ARN of the Task Role
    Value: !GetAtt TaskRole.Arn

# To deploy this template, run:
# aws cloudformation deploy --template-file register-batch/aws/dev/iam.yaml --stack-name dev-niconico-mylist-assistant-register-batch-iam --capabilities CAPABILITY_NAMED_IAM
