name: deploy-register

on:
  push:
    branches:
      - master
      - develop
    paths:
      - 'register/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment:
      name: ${{ github.ref == 'refs/heads/master' && 'production' || 'development' }}

    steps:
    - uses: actions/checkout@v2

    - name: AWS CLI install
      run: |
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip awscliv2.zip
        sudo ./aws/install --update
        aws --version

    - name: AWS set Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Deploy
      run: |
        aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.AWS_REGISTER_REPOSITORY_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com
        cd register
        docker build -t ${{ secrets.REGISTER_PROJECT_NAME }} .
        docker build \
          --build-arg AWS_DEFAULT_REGION=${{ secrets.AWS_DEFAULT_REGION }} \
          --build-arg S3_BUCKET_NAME=${{ secrets.S3_BUCKET_NAME }} \
          --build-arg SHARED_SECRET_KEY=${{ secrets.SHARED_SECRET_KEY }} \
          -t ${{ secrets.REGISTER_PROJECT_NAME }} .
        docker tag ${{ secrets.REGISTER_PROJECT_NAME }}:latest ${{ secrets.AWS_REGISTER_REPOSITORY_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.REGISTER_PROJECT_NAME }}:latest
        docker push ${{ secrets.AWS_REGISTER_REPOSITORY_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.REGISTER_PROJECT_NAME }}:latest

    - name: Update Lambda Function
      run: |
        aws lambda update-function-code --function-name ${{ secrets.REGISTER_PROJECT_NAME }} --image-uri ${{ secrets.AWS_REGISTER_REPOSITORY_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.REGISTER_PROJECT_NAME }}:latest
